server:
  listen_addr: ":53"
  geoip_db_path: "./GeoLite2-City.mmdb"
  throttling:
    rps: 10
    burst: 20

zones:
  "app.example.com.":
    ttl: 30
    pools:
      - name: "us-east"
        lat: 39.04
        lon: -77.48
        ips: ["192.168.1.10", "192.168.1.11"]
      - name: "eu-central"
        lat: 50.11
        lon: 8.68
        ips: ["1.2.3.4"]